### ISSUE TITLE
[IMPROVEMENT] : Update UI of contact us section

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#5]
Already @AmitBarman99 gave it a better look but feel free to make the UI of contact section more better.

**Comment by Brainiac-M** [comment]
Hi @PritamSarbajna, I noticed that when mouse is hovering on the icons for location, email and contact number under the Contact section, the texts in the box turns to white instead of pink. It only turns to pink when mouse is hovering on anywhere in the box aside the icon. I think I can help fix this

![image](https://user-images.githubusercontent.com/49205684/184853845-2f47aff0-5b4f-4afd-be9b-c67a152d5b44.png)

**Comment by lubnafathima** [comment]
@PritamSarbajna Could you please assign me to do this?

**Comment by Techkrish1** [comment]
can you assign this issue to me?

**Comment by PritamSarbajna** [comment]
Hey @lubnafathima you are already assigned to a issue

**Comment by Brainiac-M** [comment]
Can I work on it?

**Comment by PritamSarbajna** [comment]
yeah sure @Brainiac-M here you go

**Comment by Brainiac-M** [comment]
Alright

**Comment by Brainiac-M** [comment]
I have fixed the issue. Kindly refer to #45

**Comment by krshnknsr21** [comment]
Hey if this issue is still open can I take it up?

**Comment by PritamSarbajna** [comment]
Hey @krshnknsr21 sure go for it 🙌

**Comment by krshnknsr21** [comment]
Hey I noticed that the navbar button for contact is styled differently. Can I change it to match the styling of the other buttons?

**Comment by PritamSarbajna** [comment]
Yeah sure @krshnknsr21 🚀
